name: Deploy Backend to AWS EC2

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        cd Springboot-API-REST-DESPACHO
        chmod +x mvnw
        ./mvnw clean package -DskipTests

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        cd Springboot-API-REST-DESPACHO
        docker build -t ${{ secrets.DOCKER_USERNAME }}/back-despacho:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/back-despacho:latest

    - name: SSH Deployment to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_IP }}
        username: ubuntu
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          cd ~/Springboot-API-REST-DESPACHO
          sudo docker-compose down || true
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/back-despacho:latest
          sudo docker-compose up -d