version: '3.8'

services:
  # 1. Base de Datos (MySQL) - Requisito de Persistencia
  db_despachos:
    image: mysql:8.0
    container_name: mysql_despachos_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_seguro
      MYSQL_DATABASE: bdd_despachos
      MYSQL_USER: user_despachos
      MYSQL_PASSWORD: password_despachos
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - innovatech_network

  # 2. API Backend (Spring Boot)
  back_despachos:
    build:
      context: ./Springboot-API-REST-DESPACHO
      dockerfile: DockerFile
    container_name: spring_despachos_container
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_despachos:3306/bdd_despachos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=user_despachos
      - SPRING_DATASOURCE_PASSWORD=password_despachos
    depends_on:
      - db_despachos
    networks:
      - innovatech_network

# Configuración de Volúmenes y Redes Aisladas (Exigido en Rúbrica)
volumes:
  mysql_data:

networks:
  innovatech_network:
    driver: bridge